name: ✨ Feature Request
description: Suggest a new feature for the TRIJOSHH Attendance System
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for the TRIJOSHH Employee Attendance Tracker!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: This feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: The feature should work like...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      options:
        - Authentication & Security
        - Location Tracking
        - Work Log Management
        - Admin Dashboard
        - Reporting & Analytics
        - User Interface
        - Data Management
        - Mobile Experience
        - Integration
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      options:
        - Low
        - Medium
        - High
        - Critical

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions or features you've considered?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.